# TRAEFIK SSL CERTIFICATES - DECODED FILES
# Auto-generated by Shared Vault Agent
# Generated: {{ timestamp }}

{{- with secret "secret/data/certificates/traefik" }}
# This template generates decoded certificate files
# Files will be created in /vault/secrets/certs/

# Script to decode certificates
cat > /vault/secrets/decode-certs.sh << 'DECODE_SCRIPT'
#!/bin/sh
echo "Decoding certificates from Vault Agent..."

# Create certificates directory
mkdir -p /vault/secrets/certs

# Write fullchain (already decoded by Vault)
cat > /vault/secrets/certs/fullchain.crt << 'EOF'
{{ .Data.data.fullchain }}
EOF
echo "fullchain.crt written"

# Write private key (already decoded by Vault)
cat > /vault/secrets/certs/server.key << 'EOF'
{{ .Data.data.private_key }}
EOF
echo "server.key written"

# Write CA cert (already decoded by Vault)
cat > /vault/secrets/certs/ca.crt << 'EOF'
{{ .Data.data.ca_cert }}
EOF
echo "ca.crt written"

# Set correct permissions
chmod 600 /vault/secrets/certs/server.key
chmod 644 /vault/secrets/certs/fullchain.crt
chmod 644 /vault/secrets/certs/ca.crt

# Certificates are ready for Traefik in /vault/secrets/certs/
echo "Certificates available for Traefik:"
echo "  - /vault/secrets/certs/fullchain.crt"
echo "  - /vault/secrets/certs/server.key"
echo "  - /vault/secrets/certs/ca.crt"

echo "Certificates decoded and ready in /vault/secrets/certs/"
DECODE_SCRIPT

chmod +x /vault/secrets/decode-certs.sh
{{- end }}
