# LINKDING SERVICE SECRETS
# Auto-generated by Shared Vault Agent
# Generated: {{ timestamp }}

{{- with secret "secret/data/linkding" }}
# Linkding variables from Vault
{{- range $key, $value := .Data.data }}
{{ $key }}={{ $value }}
{{- end }}

# Shared Vault Agent metadata
VAULT_AGENT_SERVICE=linkding
VAULT_AGENT_GENERATED=true
VAULT_AGENT_TIMESTAMP={{ timestamp }}
VAULT_AGENT_TYPE=shared
{{- end }}
