# SPEEDTEST TRACKER SECRETS
# Auto-generated by Shared Vault Agent
# Generated: {{ timestamp }}
# DO NOT COMMIT THIS FILE

{{- with secret "secret/data/speedtest-tracker" }}
APP_KEY={{ .Data.data.app_key }}
{{- end }}
